{
 "title": "My service dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Active HTTP Client Connection",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\", __name__=\"http_client_open_connections\", http_connection_state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idel HTTP Client Connection",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\", __name__=\"http_client_open_connections\", http_connection_state=\"idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "filters": [
      { "id": "33e4ff8b", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "resource.service.name=\"$service_name\"",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Log - Warning",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\"} | json | severity_text = \"Warning\""
    }
   ]
  },
  {
   "title": "Log - Error",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\"} | json | severity_text = \"Error\""
    }
   ]
  },
  {
   "title": "Log - Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\"} | json | severity_text = \"Information\""
    }
   ]
  }
 ]
}