version: "3.8"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/var/loki
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo-config.yaml"]
    volumes:
      - ./tempo-config.yaml:/etc/tempo-config.yaml
      - ./data/tempo:/var/tempo
    ports:
      - "3200:3200"
      - "9096:9096"
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - loki
      - tempo

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1234
    depends_on:
      - loki
      - tempo
      - prometheus

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      [
        "--config=/etc/otelcol-config.yaml",
        "--feature-gates=service.profilesSupport",
      ]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
      - ./otelcol-config-export-http.yaml:/etc/otelcol-config-export-http.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
      - tempo
      - prometheus
